### ISSUE TITLE
Can't install?

### ISSUE THREAD

**Issue by bradparks** [sindresorhus/slugify#6]
Hey! I'm probably too much of a newb here, but I can install all of your node modules so far, except this one ;-)

I'm using node v8.10.0, and npm 5.6.0. Thanks!

```
$ npm install @sindresorhus/slugify
npm ERR! code E404
npm ERR! 404 Not Found: @sindresorhus/slugify@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bparks/.npm/cache/_logs/2018-04-27T11_36_52_196Z-debug.log
```

and that log file has this in it

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/bparks/.nvm/versions/node/v8.10.0/bin/node',
1 verbose cli   '/Users/bparks/.nvm/versions/node/v8.10.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@sindresorhus/slugify' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose npm-session 1b1c4188ad8951d9
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://nexus.dev.ca3.sfmc.co/nexus/content/repositories/npm-all/@sindresorhus%2fslugify 859ms
8 silly fetchPackageMetaData error for @sindresorhus/slugify@latest 404 Not Found: @sindresorhus/slugify@latest
9 verbose stack Error: 404 Not Found: @sindresorhus/slugify@latest
9 verbose stack     at fetch.then.res (/Users/bparks/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/Users/bparks/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/Users/bparks/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/Users/bparks/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/Users/bparks/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/Users/bparks/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/Users/bparks/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/Users/bparks/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/Users/bparks/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:794:20)
9 verbose stack     at tryOnImmediate (timers.js:752:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
10 verbose cwd /Users/bparks/bin/node_scripts
11 verbose Darwin 17.5.0
12 verbose argv "/Users/bparks/.nvm/versions/node/v8.10.0/bin/node" "/Users/bparks/.nvm/versions/node/v8.10.0/bin/npm" "install" "@sindresorhus/slugify"
13 verbose node v8.10.0
14 verbose npm  v5.6.0
15 error code E404
16 error 404 Not Found: @sindresorhus/slugify@latest
17 verbose exit [ 1, true ]
```

**Comment by sindresorhus** [comment]
Use the npm issue tracker for npm install issues. This is not really related to this module specifically. Maybe you have some alternative registry specified to causes problems with this package since it’s a scopes package.
